### ISSUE TITLE
Byts run together

### ISSUE THREAD

**Issue by pmartel** [sparkfun/SparkFun_Qwiic_RFID_ID-XXLA#4]
### Subject of the issue
No separation between bytes in Example1_ReadTag.ino

### Your workbench
Windows 10, Arduino 1.6,6 and 1.8.9
* What version of the device are you using? Is there a firmware version?
USB
USB
* Are there any additional details that may help us help you?

### Steps to reproduce
Run it.  Notice that the bytes may be between 1 and 3 digits.  There is no clear separation between the bytes.
### Expected behaviour
Either put a separator between bytes, or express them in hex and put a '0' in front of '0' to 'f'
	for( int x = 0; x < TAG_REQUEST; x++ ) {
    tempTag = Wire.read(); 
    // Concatenating the bytes onto the end of "tagID".
    s = String(tempTag, HEX); // s is defined as a String 
    if ( s.length() == 1) { // handle 00 through 0f
      s = "0"+s;
    }
    tagID += s; 
  }
### Actual behaviour
bytes are ambiguous

**Comment by edspark** [comment]
That's an interesting perspective. While the incoming bytes certainly could be broken up or printed out as a HEX, I don't see how that gives greater clarity to the RFID tag number because it _is_ that number. If you look at the datasheet for the module on the module's product page under the "Documents" tab found [here](https://www.sparkfun.com/products/11827). There is a section on page four that explains the format of the RFID tag number: five numerical values followed by a checksum of those five numbers. This is what's presented by the module to the SparkFun RFID IDxx-LA  and then passed to you the user.  It's like splitting the number 196 into it's individual numerical components (1 - 9 - 6), but really the number is 196.  Re-open the issue if I missed something. Thanks for issue!

**Comment by pmartel** [comment]
Give that you know that there are 5 bytes and a checksum, I agree that you should be able to extract the bytes from a string of decimal digits.  However, if you want to verify the checksum, it becomes somewhat messy.
Here are the tag numbers for the 2 cards that came with my kit and another RFID device I have:
SparkFun Qwiic RFID, waiting for RFID to be scanned.
RFID Tag ID: 850898172147
RFID Tag ID: 850723432152
RFID Tag ID: 78097123228176

I wondered about the different lengths of the strings.  That led me to realize that there were no delimiters between the bytes and potential ambiguity.  If you had to take one of those RFID tag IDs and verify the checksum, how would you proceed?

**Comment by edspark** [comment]
I like where you're brain is going! Before I begin, I want you to know that the module does a checksum on the bytes before it sends them serially to the SparkFun Qwiic RFID-IDxxLA, and then I unnecessarily do an _additional_ checksum on the number before I send it to the user. With that said, I would encourage you to read the datasheet (again page four) as it explains how it is done quite clearly with pictures, however I'll do my best to explain it in text.  Each column of bits of each _byte_ is exclusively or'ed (EXOR'ed) with each other to get the checksum.  If you wanted to get it done with provided code, you would print out each byte with the Serial.println(tempTag, BIN), then EXOR the first column of bits, then the second column bits, then the third, etc. and those EXOR'ed bits together will equal the sixth checksum byte.  Hope that helps.

**Comment by pmartel** [comment]
Thanks, I'm familiar with checksums.  We used to do them on paper tape a long time ago.Given the individual bytes, it's straightforward to do a checksum, and of course the checksum of all 6 bytes should be 0.  I was just trying to point out that when the decimal representations of the bytes are merged together into a string, it's a bit tougher to verify the checksum.
Best wishes,--Phil
In a message dated 4/2/2019 12:44:45 Eastern Standard Time, notifications@github.com writes:


I like where you're brain is going! Before I begin, I want you to know that the module does a checksum on the bytes before it sends them serially to the SparkFun Qwiic RFID-IDxxLA, and then I unnecessarily do an additional checksum on the number before I send it to the user. With that said, I would encourage you to read the datasheet (again page four) as it explains how it is done quite clearly with pictures, however I'll do my best to explain it in text. Each column of bits of each byte is exclusively or'ed (EXOR'ed) with each other to get the checksum. If you wanted to get it done with provided code, you would print out each byte with the Serial.println(tempTag, BIN), then EXOR the first column of bits, then the second column bits, then the third, etc. and those EXOR'ed bits together will equal the sixth checksum byte. Hope that helps.
